### ISSUE TITLE
Export for Gate Cloud with String Annotation getting Exception

### ISSUE THREAD

**Issue by krishnareddyML** [GateNLP/gateplugin-StringAnnotation#21]
Getting following error while I am trying to export ANNIE and String Annotation plugins using 

**Export to Gate Cloud option** 

**GATE Version: 8.5.1**
```
**Error cacheing plugin uk.ac.gate.plugins:stringannotation:4.1
	at gate.util.ant.packager.PackageGappTask.execute(PackageGappTask.java:698)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at gate.gui.NameBearerHandle$ExportApplicationAction$1.run(NameBearerHandle.java:884)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.maven.model.building.ModelBuildingException: 1 problem was encountered while building the effective model for commons-cli:commons-cli:1.4
[ERROR] Failed to determine Java version for profile jdk7-plugin-fix-version @ org.apache.commons:commons-parent:42

	at org.apache.maven.model.building.DefaultModelProblemCollector.newModelBuildingException(DefaultModelProblemCollector.java:197)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:482)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:424)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:414)
	at gate.util.maven.SimpleMavenCache.cacheParents(SimpleMavenCache.java:176)
	at gate.util.maven.SimpleMavenCache.cacheArtifact(SimpleMavenCache.java:160)
	at gate.util.ant.packager.PackageGappTask.execute(PackageGappTask.java:694)
	... 8 more**
```

**Comment by greenwoodma** [comment]
Yes, I can't quite remember what the problem was but this is fixed in 8.6-SNAPSHOT (I just double checked to be sure)
